#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me
# is redirecting to https://chat.openai.com/

sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://chat.openai.com/ permanent;' /etc/nginx/sites-available/default
