#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me
# is redirecting to https://chat.openai.com/

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://chat.openai.com/ permanent; \n error_page 404 /404.html; \n add_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default
service nginx reload
