#!/usr/bin/env bash
# configures loadbalancer

sudo apt-get update
sudo apt-get install -y haproxy

server_config=\
"
        bind *:80
        mode http
        balance roundrobin
        server 176572-web-01 54.165.168.252:80 check
        server 176572-web-02 34.237.91.136:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
