#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

l=$(ls)
for name in $l; do echo "$name" | cut -d '-' -f 2; done

